pipeline {
    agent any
    tools {
        maven 'maven-3.8'
    }


    environment {
    APP_NAME = "lifpay-gateway"
    IMAGE_TAG = "v1.0"
    IMAGE_NAME = "${APP_NAME}:${IMAGE_TAG}"
    PORT = 9001
    NAMESPACE = "lifpay-test"
    //定义构建目录，方便清理
    BUILD_DIR = "${WORKSPACE}/parent/${APP_NAME}"
    }

    stages {
        stage('前置清理') {
            steps {
                echo "==================开始清理历史构建资源===================="
                sh "kubectl delete pod -n ${NAMESPACE} -l app=${APP_NAME} --force --grace-period=0 || true"
                sh "rm -rf ${BUILD_DIR}/target || true"
                sh "rm -rf ${WORKSPACE}/parent/target || true"
                sh "rm -rf ${WORKSPACE}/@tmp || true"
                echo "===================历史资源清理完成======================"
            }
        }


        stage('拉取代码') {
            steps {
                checkout scm
            }
        }


        stage('Maven打包') {
            steps {
               dir("parent") {
                   sh "mvn clean package -pl ${APP_NAME} -am -DskipTests"
               }


            }
        }

        stage('构建镜像') {
            steps {
                dir("parent/${APP_NAME}") {
                    sh "docker stop ${APP_NAME} || true"
                    sh "docker rm ${APP_NAME} || true"
                    sh "docker rmi ${IMAGE_NAME} || true"
                    sh "docker build -t ${IMAGE_NAME} ."
                    sh "docker images | grep ${IMAGE_NAME}"
                }
            }
        }

        // 推送镜像（暂时忽略）

       stage('部署到k3s集群') {
            steps {
                dir("parent/${APP_NAME}") {
                    sh '''
                    kubectl apply --dry-run=client -f deploy.yaml -n ${NAMESPACE}
                    kubectl apply -f deploy.yaml -n ${NAMESPACE}
                    kubectl get pods -n ${NAMESPACE} -l app=${APP_NAME}
                    kubectl get svc -n ${NAMESPACE} ${APP_NAME}-service
                    '''
                }
            }


       }

    }

    post {
        success {
            echo "===== 流水线执行成功！服务已部署成功 ====="
            sh '''
                echo "应用名称：${APP_NAME}"
                echo "镜像版本：${IMAGE_NAME}"
                echo "访问地址：http://$(hostname -I | awk '{print $1}'):30901"
                echo "命令空间：${NAMESPACE}"
            '''
        }
        failure {
            echo "===== 流水线执行失败！====="
            // 失败时打印容器日志，方便排查
            sh "kubectl logs -n ${NAMESPACE} -l app=${APP_NAME} || true"
        }
        always {
            echo "===== 执行最终清理 ====="
            sh "rm -rf ${BUILD_DIR} || true"
            sh "rm -rf ${BUILD_DIR}/${APP_NAME}.tar || true"
        }

    }


}